version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: "@babel/runtime"
    versions:
    - 7.13.16
  - dependency-name: cypress
    versions:
    - 6.7.0
    - 6.7.1
  - dependency-name: rollup-plugin-svelte
    versions:
    - 7.1.0
  - dependency-name: tailwindcss
    versions:
    - 2.0.2
